### ISSUE TITLE
14.3 hook swift print 无效果？

### ISSUE THREAD

**Issue by lgq2015** [kagenZhao/LogInWindow#1]

**Comment by kagenZhao** [comment]
14.4模拟器我运行demo是有打印的, 14.3我还在下载中.... 要不加qq讨论一下 :1149467687
![image](https://user-images.githubusercontent.com/15279361/109123780-292b6e80-7785-11eb-8d0c-b5f248c0bb67.png)

**Comment by kagenZhao** [comment]
谢谢提醒, 真机确实有问题, 暂时改为dup2+pipe的方式重定向输出, 如果有更好的方式唤醒提交PR
